server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway


#配置前:http://localhost:8001/dept/get/1
#http://myzuul.com:9527/atguigu/mydept/dept/get/1
#分解解释:http://myzuul.com:9527这个工程,zuul注入到注册中心中,就会接管所有的注册中心
#/atguigu配置前置名字
#/mydept  配置microservicecloud-dept这个服务就叫做/mydept
#/dept/get/1   需要访问的方法
zuul:
  prefix: /atguigu
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**



eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
